#! /usr/bin/env bash
set -e
set -u
S_NAME=rkdev
log() {
	msg="LOG: $S_NAME> $*"
	echo "$(date +'%Y-%m-%dT%H:%M:%S.%3N%z'):" "$msg" >&2
}

err() {
	msg="ERROR: $S_NAME> $*"
	echo "$(date +'%Y-%m-%dT%H:%M:%S.%3N%z'):" "$msg" >&2
	exit 100
}

warn() {
	msg="WARN: $S_NAME> $*"
	echo "$(date +'%Y-%m-%dT%H:%M:%S.%3N%z'):" "$msg" >&2
}

# Get current work directory
script="$(realpath "$0")"
script_path="$(dirname "$script")"
cd "${script_path}" || {
	echo "initialize work dir failed"
	exit 1
}

workspace="$script_path"
log "workspace: $workspace"

"$workspace/./rkdeveloptool_arm64_linux/ld-linux-aarch64.so.1" \
	"--library-path" "$workspace/./rkdeveloptool_arm64_linux/" \
	"$workspace/./rkdeveloptool_arm64_linux/rkdeveloptool" "$@"
